name: build-modupdater
on: 
  workflow_dispatch:
    inputs:
      fancyname:
        description: 'Fancy Release Name'
        required: false
        type: string
      commit:
        description: 'Include Commit in Name'
        default: true
        type: boolean

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: install dependencies
        run: bun install

      - name: build binaries
        run: bun run build-all

      - name: get version
        run: |
          echo "tagname=$(./out/modupdater-linux --version)-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "releasename=$(./out/modupdater-linux --version)$(if [ ${{inputs.commit}} = true ]; then echo "-$(git rev-parse --short HEAD)"; fi)$(if [ ${{inputs.fancyname}} ]; then echo " ${{inputs.fancyname}}"; fi)" >> $GITHUB_OUTPUT
        env: 
          FANCYNAME: ${{ inputs.fancyname }}
          COMMIT: ${{ inputs.commit }}
        id: version

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: out/*
          draft: false
          prerelease: false
          tag_name: ${{ steps.version.outputs.tagname }}
          name: ${{ steps.version.outputs.releasename }}
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}