name: build-modupdater
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build-all
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: out