name: build-modupdater
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: install dependencies
        run: bun install

      - name: build binaries
        run: bun run build-all

      - name: get version
        run: echo "::set-output name=version::$(./out/modupdater --version)-$(git rev-parse --short HEAD)"
        id: version

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: ${{ steps.version.outputs.version }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/modupdater-linux
            out/modupdater-windows.exe
        env:
          GITHUB_TOKEN: ${{ github.token }}